### ISSUE TITLE
The (STG Sequel) link is causing issues.

### ISSUE THREAD

**Issue by 3rdman** [cohomolo-gy/haskell-resources#11]
The parens around STG Sequel are confusing the reducer.

```node
TypeError [ERR_INVALID_URL]: Invalid URL: STG Sequel)](https://www.cs.tufts.edu/comp/150FP/archive/simon-peyton-jones/eval-apply-jfp.pdf
    at new NodeError (node:internal/errors:363:5)
    at onParseError (node:internal/url:537:9)
    at new URL (node:internal/url:613:5)
    at request (node:https:303:32)
    at Object.get (node:https:321:15)
    at /Users/rd/public-src/github.com/cohomolo-gy/haskell-resources/download.js:25:27
    at /Users/rd/public-src/github.com/cohomolo-gy/haskell-resources/download.js:9:8
    at new Promise (<anonymous>)
    at /Users/rd/public-src/github.com/cohomolo-gy/haskell-resources/download.js:8:37
    at /Users/rd/public-src/github.com/cohomolo-gy/haskell-resources/download.js:58:10 {
  input: 'STG Sequel)](https://www.cs.tufts.edu/comp/150FP/archive/simon-peyton-jones/eval-apply-jfp.pdf',
  code: 'ERR_INVALID_URL'
}
```

**Comment by emilypi** [comment]
Thanks for reporting @3rdman! I've fixed the regex and it works now.
